export type MessageStickerDefinition = {
  key: string;
  label: string;
  character: string;
  imageUrl: string;
  width: number;
  height: number;
};

/**
 * Public sticker artwork is committed under public/assets/message-stickers.
 * Keep the browser catalog on same-origin paths so opening the sticker picker
 * never depends on a third-party image host or hotlink availability.
 */
export const MESSAGE_STICKER_CATALOG: readonly MessageStickerDefinition[] = [
  {
    key: 'hello-kitty-01',
    label: '挥挥手',
    character: 'Hello Kitty',
    imageUrl: '/assets/message-stickers/hello-kitty-01.png',
    width: 88,
    height: 94,
  },
  {
    key: 'kuromi-01',
    label: '小恶魔',
    character: '酷洛米',
    imageUrl: '/assets/message-stickers/kuromi-01.png',
    width: 88,
    height: 96,
  },
  {
    key: 'my-melody-01',
    label: '粉粉的',
    character: '美乐蒂',
    imageUrl: '/assets/message-stickers/my-melody-01.png',
    width: 90,
    height: 98,
  },
  {
    key: 'pompompurin-01',
    label: '困困布丁',
    character: '布丁狗',
    imageUrl: '/assets/message-stickers/pompompurin-01.png',
    width: 96,
    height: 88,
  },
  {
    key: 'pochacco-01',
    label: '来玩呀',
    character: '帕恰狗',
    imageUrl: '/assets/message-stickers/pochacco-01.png',
    width: 90,
    height: 96,
  },
  {
    key: 'keroppi-01',
    label: '元气青蛙',
    character: '大眼蛙',
    imageUrl: '/assets/message-stickers/keroppi-01.png',
    width: 88,
    height: 82,
  },
  {
    key: 'gudetama-01',
    label: '今天躺平',
    character: '蛋黄哥',
    imageUrl: '/assets/message-stickers/gudetama-01.png',
    width: 104,
    height: 72,
  },
  {
    key: 'badtz-maru-01',
    label: '拽拽的',
    character: '酷企鹅',
    imageUrl: '/assets/message-stickers/badtz-maru-01.png',
    width: 88,
    height: 96,
  },
  {
    key: 'chococat-01',
    label: '黑猫探头',
    character: '巧克猫',
    imageUrl: '/assets/message-stickers/chococat-01.png',
    width: 86,
    height: 96,
  },
  {
    key: 'cinnamoroll-heart-01',
    label: '送你爱心',
    character: '玉桂狗',
    imageUrl: '/assets/message-stickers/cinnamoroll-heart-01.png',
    width: 72,
    height: 110,
  },
  {
    key: 'kuromi-heart-01',
    label: '酷洛米爱心',
    character: '酷洛米',
    imageUrl: '/assets/message-stickers/kuromi-heart-01.png',
    width: 88,
    height: 96,
  },
  {
    key: 'my-melody-heart-01',
    label: '抱住爱心',
    character: '美乐蒂',
    imageUrl: '/assets/message-stickers/my-melody-heart-01.png',
    width: 88,
    height: 100,
  },
  {
    key: 'nekoha-shizuku-wave-01',
    label: '雫 · 01',
    character: '猫羽雫',
    imageUrl: '/assets/message-stickers/nekoha-shizuku-wave-01.png',
    width: 96,
    height: 96,
  },
  {
    key: 'nekoha-shizuku-hug-01',
    label: '雫 · 02',
    character: '猫羽雫',
    imageUrl: '/assets/message-stickers/nekoha-shizuku-hug-01.png',
    width: 96,
    height: 96,
  },
  {
    key: 'nekoha-shizuku-cheer-01',
    label: '雫 · 03',
    character: '猫羽雫',
    imageUrl: '/assets/message-stickers/nekoha-shizuku-cheer-01.png',
    width: 96,
    height: 96,
  },
  {
    key: 'nachoneko-love-01',
    label: '猫猫 · 01',
    character: '甘城猫猫',
    imageUrl: '/assets/message-stickers/nachoneko-love-01.png',
    width: 94,
    height: 96,
  },
  {
    key: 'nachoneko-peek-01',
    label: '猫猫 · 02',
    character: '甘城猫猫',
    imageUrl: '/assets/message-stickers/nachoneko-peek-01.png',
    width: 108,
    height: 82,
  },
  {
    key: 'nachoneko-pizza-01',
    label: '猫猫 · 03',
    character: '甘城猫猫',
    imageUrl: '/assets/message-stickers/nachoneko-pizza-01.png',
    width: 108,
    height: 82,
  },
  {
    key: 'nekoha-shizuku-04',
    label: '雫 · 04',
    character: '猫羽雫',
    imageUrl: '/assets/message-stickers/nekoha-shizuku-04.png',
    width: 96,
    height: 96,
  },
  {
    key: 'nekoha-shizuku-05',
    label: '雫 · 05',
    character: '猫羽雫',
    imageUrl: '/assets/message-stickers/nekoha-shizuku-05.png',
    width: 96,
    height: 96,
  },
  {
    key: 'nekoha-shizuku-06',
    label: '雫 · 06',
    character: '猫羽雫',
    imageUrl: '/assets/message-stickers/nekoha-shizuku-06.png',
    width: 96,
    height: 96,
  },
  {
    key: 'nekoha-shizuku-07',
    label: '雫 · 07',
    character: '猫羽雫',
    imageUrl: '/assets/message-stickers/nekoha-shizuku-07.png',
    width: 96,
    height: 96,
  },
  {
    key: 'nachoneko-cry-02',
    label: '猫猫 · 04',
    character: '甘城猫猫',
    imageUrl: '/assets/message-stickers/nachoneko-cry-02.png',
    width: 96,
    height: 96,
  },
  {
    key: 'nachoneko-angry-02',
    label: '猫猫 · 05',
    character: '甘城猫猫',
    imageUrl: '/assets/message-stickers/nachoneko-angry-02.png',
    width: 96,
    height: 96,
  },
  {
    key: 'nachoneko-donut-02',
    label: '猫猫 · 06',
    character: '甘城猫猫',
    imageUrl: '/assets/message-stickers/nachoneko-donut-02.png',
    width: 96,
    height: 96,
  },
  {
    key: 'nachoneko-sorry-02',
    label: '猫猫 · 07',
    character: '甘城猫猫',
    imageUrl: '/assets/message-stickers/nachoneko-sorry-02.png',
    width: 96,
    height: 96,
  },
  {
    key: 'pochacco-play-02',
    label: '帕恰狗 · 02',
    character: '帕恰狗',
    imageUrl: '/assets/message-stickers/pochacco-play-02.png',
    width: 92,
    height: 92,
  },
  {
    key: 'pochacco-kawaii-03',
    label: '帕恰狗 · 03',
    character: '帕恰狗',
    imageUrl: '/assets/message-stickers/pochacco-kawaii-03.png',
    width: 92,
    height: 92,
  },
  {
    key: 'pochacco-fun-04',
    label: '帕恰狗 · 04',
    character: '帕恰狗',
    imageUrl: '/assets/message-stickers/pochacco-fun-04.png',
    width: 92,
    height: 92,
  },
  {
    key: 'pochacco-friends-05',
    label: '帕恰狗 · 05',
    character: '帕恰狗',
    imageUrl: '/assets/message-stickers/pochacco-friends-05.png',
    width: 92,
    height: 92,
  },
  {
    key: 'journal-sparkles-01',
    label: '闪闪发光',
    character: '手帐装饰',
    imageUrl: '/assets/message-stickers/journal-sparkles-01.png',
    width: 80,
    height: 80,
  },
  {
    key: 'journal-blossom-01',
    label: '樱花一朵',
    character: '手帐装饰',
    imageUrl: '/assets/message-stickers/journal-blossom-01.png',
    width: 80,
    height: 80,
  },
] as const;

export const MESSAGE_STICKER_BY_KEY = new Map(
  MESSAGE_STICKER_CATALOG.map((item) => [item.key, item] as const),
);
