export type MessageStickerCategory = 'sanrio' | 'nekoha-shizuku' | 'nachoneko' | 'journal';

export type MessageStickerDefinition = {
  key: string;
  label: string;
  character: string;
  category: MessageStickerCategory;
  imageUrl: string;
  width: number;
  height: number;
};

/**
 * Public sticker artwork is committed under public/assets/message-stickers.
 * Keep the browser catalog on same-origin paths so opening the sticker picker
 * never depends on a third-party image host or hotlink availability.
 */
export const MESSAGE_STICKER_CATALOG: readonly MessageStickerDefinition[] = [
  {
    key: 'hello-kitty-01',
    label: '挥挥手',
    category: 'sanrio',
    character: 'Hello Kitty',
    imageUrl: '/assets/message-stickers/hello-kitty-01.png',
    width: 88,
    height: 94,
  },
  {
    key: 'kuromi-01',
    label: '小恶魔',
    category: 'sanrio',
    character: '酷洛米',
    imageUrl: '/assets/message-stickers/kuromi-01.png',
    width: 88,
    height: 96,
  },
  {
    key: 'my-melody-01',
    label: '粉粉的',
    category: 'sanrio',
    character: '美乐蒂',
    imageUrl: '/assets/message-stickers/my-melody-01.png',
    width: 90,
    height: 98,
  },
  {
    key: 'pompompurin-01',
    label: '困困布丁',
    category: 'sanrio',
    character: '布丁狗',
    imageUrl: '/assets/message-stickers/pompompurin-01.png',
    width: 96,
    height: 88,
  },
  {
    key: 'pochacco-01',
    label: '来玩呀',
    category: 'sanrio',
    character: '帕恰狗',
    imageUrl: '/assets/message-stickers/pochacco-01.png',
    width: 90,
    height: 96,
  },
  {
    key: 'keroppi-01',
    label: '元气青蛙',
    category: 'sanrio',
    character: '大眼蛙',
    imageUrl: '/assets/message-stickers/keroppi-01.png',
    width: 88,
    height: 82,
  },
  {
    key: 'gudetama-01',
    label: '今天躺平',
    category: 'sanrio',
    character: '蛋黄哥',
    imageUrl: '/assets/message-stickers/gudetama-01.png',
    width: 104,
    height: 72,
  },
  {
    key: 'badtz-maru-01',
    label: '拽拽的',
    category: 'sanrio',
    character: '酷企鹅',
    imageUrl: '/assets/message-stickers/badtz-maru-01.png',
    width: 88,
    height: 96,
  },
  {
    key: 'chococat-01',
    label: '黑猫探头',
    category: 'sanrio',
    character: '巧克猫',
    imageUrl: '/assets/message-stickers/chococat-01.png',
    width: 86,
    height: 96,
  },
  {
    key: 'cinnamoroll-heart-01',
    label: '送你爱心',
    category: 'sanrio',
    character: '大耳狗',
    imageUrl: '/assets/message-stickers/cinnamoroll-heart-01.png',
    width: 72,
    height: 110,
  },
  {
    key: 'kuromi-heart-01',
    label: '酷洛米爱心',
    category: 'sanrio',
    character: '酷洛米',
    imageUrl: '/assets/message-stickers/kuromi-heart-01.png',
    width: 88,
    height: 96,
  },
  {
    key: 'my-melody-heart-01',
    label: '抱住爱心',
    category: 'sanrio',
    character: '美乐蒂',
    imageUrl: '/assets/message-stickers/my-melody-heart-01.png',
    width: 88,
    height: 100,
  },
  {
    key: 'nekoha-shizuku-wave-01',
    label: '雫 · 01',
    category: 'nekoha-shizuku',
    character: '猫羽雫',
    imageUrl: '/assets/message-stickers/nekoha-shizuku-wave-01.png',
    width: 96,
    height: 96,
  },
  {
    key: 'nekoha-shizuku-hug-01',
    label: '雫 · 02',
    category: 'nekoha-shizuku',
    character: '猫羽雫',
    imageUrl: '/assets/message-stickers/nekoha-shizuku-hug-01.png',
    width: 96,
    height: 96,
  },
  {
    key: 'nekoha-shizuku-cheer-01',
    label: '雫 · 03',
    category: 'nekoha-shizuku',
    character: '猫羽雫',
    imageUrl: '/assets/message-stickers/nekoha-shizuku-cheer-01.png',
    width: 96,
    height: 96,
  },
  {
    key: 'nachoneko-love-01',
    label: '猫猫 · 01',
    category: 'nachoneko',
    character: '甘城猫猫',
    imageUrl: '/assets/message-stickers/nachoneko-love-01.png',
    width: 94,
    height: 96,
  },
  {
    key: 'nachoneko-peek-01',
    label: '猫猫 · 02',
    category: 'nachoneko',
    character: '甘城猫猫',
    imageUrl: '/assets/message-stickers/nachoneko-peek-01.png',
    width: 108,
    height: 82,
  },
  {
    key: 'nachoneko-pizza-01',
    label: '猫猫 · 03',
    category: 'nachoneko',
    character: '甘城猫猫',
    imageUrl: '/assets/message-stickers/nachoneko-pizza-01.png',
    width: 108,
    height: 82,
  },
  {
    key: 'nekoha-shizuku-04',
    label: '雫 · 04',
    category: 'nekoha-shizuku',
    character: '猫羽雫',
    imageUrl: '/assets/message-stickers/nekoha-shizuku-04.png',
    width: 96,
    height: 96,
  },
  {
    key: 'nekoha-shizuku-05',
    label: '雫 · 05',
    category: 'nekoha-shizuku',
    character: '猫羽雫',
    imageUrl: '/assets/message-stickers/nekoha-shizuku-05.png',
    width: 96,
    height: 96,
  },
  {
    key: 'nekoha-shizuku-06',
    label: '雫 · 06',
    category: 'nekoha-shizuku',
    character: '猫羽雫',
    imageUrl: '/assets/message-stickers/nekoha-shizuku-06.png',
    width: 96,
    height: 96,
  },
  {
    key: 'nekoha-shizuku-07',
    label: '雫 · 07',
    category: 'nekoha-shizuku',
    character: '猫羽雫',
    imageUrl: '/assets/message-stickers/nekoha-shizuku-07.png',
    width: 96,
    height: 96,
  },
  {
    key: 'nachoneko-cry-02',
    label: '猫猫 · 04',
    category: 'nachoneko',
    character: '甘城猫猫',
    imageUrl: '/assets/message-stickers/nachoneko-cry-02.png',
    width: 96,
    height: 96,
  },
  {
    key: 'nachoneko-angry-02',
    label: '猫猫 · 05',
    category: 'nachoneko',
    character: '甘城猫猫',
    imageUrl: '/assets/message-stickers/nachoneko-angry-02.png',
    width: 96,
    height: 96,
  },
  {
    key: 'nachoneko-donut-02',
    label: '猫猫 · 06',
    category: 'nachoneko',
    character: '甘城猫猫',
    imageUrl: '/assets/message-stickers/nachoneko-donut-02.png',
    width: 96,
    height: 96,
  },
  {
    key: 'nachoneko-sorry-02',
    label: '猫猫 · 07',
    category: 'nachoneko',
    character: '甘城猫猫',
    imageUrl: '/assets/message-stickers/nachoneko-sorry-02.png',
    width: 96,
    height: 96,
  },
  {
    key: 'pochacco-play-02',
    label: '帕恰狗 · 02',
    category: 'sanrio',
    character: '帕恰狗',
    imageUrl: '/assets/message-stickers/pochacco-play-02.png',
    width: 92,
    height: 92,
  },
  {
    key: 'pochacco-kawaii-03',
    label: '帕恰狗 · 03',
    category: 'sanrio',
    character: '帕恰狗',
    imageUrl: '/assets/message-stickers/pochacco-kawaii-03.png',
    width: 92,
    height: 92,
  },
  {
    key: 'pochacco-fun-04',
    label: '帕恰狗 · 04',
    category: 'sanrio',
    character: '帕恰狗',
    imageUrl: '/assets/message-stickers/pochacco-fun-04.png',
    width: 92,
    height: 92,
  },
  {
    key: 'pochacco-friends-05',
    label: '帕恰狗 · 05',
    category: 'sanrio',
    character: '帕恰狗',
    imageUrl: '/assets/message-stickers/pochacco-friends-05.png',
    width: 92,
    height: 92,
  },
  {
    key: 'journal-sparkles-01',
    label: '闪闪发光',
    category: 'journal',
    character: '手帐装饰',
    imageUrl: '/assets/message-stickers/journal-sparkles-01.png',
    width: 80,
    height: 80,
  },
  {
    key: 'journal-blossom-01',
    label: '樱花一朵',
    category: 'journal',
    character: '手帐装饰',
    imageUrl: '/assets/message-stickers/journal-blossom-01.png',
    width: 80,
    height: 80,
  },
  {
    key: 'kuromi-pack-01',
    label: '库洛米 · 01',
    category: 'sanrio',
    character: '酷洛米',
    imageUrl: '/assets/message-stickers/kuromi-pack-01.png',
    width: 96,
    height: 96,
  },
  {
    key: 'kuromi-pack-02',
    label: '库洛米 · 02',
    category: 'sanrio',
    character: '酷洛米',
    imageUrl: '/assets/message-stickers/kuromi-pack-02.png',
    width: 96,
    height: 96,
  },
  {
    key: 'kuromi-pack-03',
    label: '库洛米 · 03',
    category: 'sanrio',
    character: '酷洛米',
    imageUrl: '/assets/message-stickers/kuromi-pack-03.png',
    width: 96,
    height: 96,
  },
  {
    key: 'kuromi-pack-04',
    label: '库洛米 · 04',
    category: 'sanrio',
    character: '酷洛米',
    imageUrl: '/assets/message-stickers/kuromi-pack-04.png',
    width: 96,
    height: 96,
  },
  {
    key: 'kuromi-pack-05',
    label: '库洛米 · 05',
    category: 'sanrio',
    character: '酷洛米',
    imageUrl: '/assets/message-stickers/kuromi-pack-05.png',
    width: 96,
    height: 96,
  },
  {
    key: 'kuromi-pack-06',
    label: '库洛米 · 06',
    category: 'sanrio',
    character: '酷洛米',
    imageUrl: '/assets/message-stickers/kuromi-pack-06.png',
    width: 96,
    height: 96,
  },
  {
    key: 'kuromi-pack-07',
    label: '库洛米 · 07',
    category: 'sanrio',
    character: '酷洛米',
    imageUrl: '/assets/message-stickers/kuromi-pack-07.png',
    width: 96,
    height: 96,
  },
  {
    key: 'kuromi-pack-08',
    label: '库洛米 · 08',
    category: 'sanrio',
    character: '酷洛米',
    imageUrl: '/assets/message-stickers/kuromi-pack-08.png',
    width: 96,
    height: 96,
  },
  {
    key: 'kuromi-pack-09',
    label: '库洛米 · 09',
    category: 'sanrio',
    character: '酷洛米',
    imageUrl: '/assets/message-stickers/kuromi-pack-09.png',
    width: 96,
    height: 96,
  },
  {
    key: 'kuromi-pack-10',
    label: '库洛米 · 10',
    category: 'sanrio',
    character: '酷洛米',
    imageUrl: '/assets/message-stickers/kuromi-pack-10.png',
    width: 96,
    height: 96,
  },
  {
    key: 'kuromi-pack-11',
    label: '库洛米 · 11',
    category: 'sanrio',
    character: '酷洛米',
    imageUrl: '/assets/message-stickers/kuromi-pack-11.png',
    width: 96,
    height: 96,
  },
  {
    key: 'kuromi-pack-12',
    label: '库洛米 · 12',
    category: 'sanrio',
    character: '酷洛米',
    imageUrl: '/assets/message-stickers/kuromi-pack-12.png',
    width: 96,
    height: 96,
  },
  {
    key: 'kuromi-pack-13',
    label: '库洛米 · 13',
    category: 'sanrio',
    character: '酷洛米',
    imageUrl: '/assets/message-stickers/kuromi-pack-13.png',
    width: 96,
    height: 96,
  },
  {
    key: 'kuromi-pack-14',
    label: '库洛米 · 14',
    category: 'sanrio',
    character: '酷洛米',
    imageUrl: '/assets/message-stickers/kuromi-pack-14.png',
    width: 96,
    height: 96,
  },
  {
    key: 'cinnamoroll-pack-01',
    label: '大耳狗 · 01',
    category: 'sanrio',
    character: '大耳狗',
    imageUrl: '/assets/message-stickers/cinnamoroll-pack-01.png',
    width: 96,
    height: 96,
  },
  {
    key: 'cinnamoroll-pack-02',
    label: '大耳狗 · 02',
    category: 'sanrio',
    character: '大耳狗',
    imageUrl: '/assets/message-stickers/cinnamoroll-pack-02.png',
    width: 96,
    height: 96,
  },
  {
    key: 'cinnamoroll-pack-03',
    label: '大耳狗 · 03',
    category: 'sanrio',
    character: '大耳狗',
    imageUrl: '/assets/message-stickers/cinnamoroll-pack-03.png',
    width: 96,
    height: 96,
  },
  {
    key: 'cinnamoroll-pack-04',
    label: '大耳狗 · 04',
    category: 'sanrio',
    character: '大耳狗',
    imageUrl: '/assets/message-stickers/cinnamoroll-pack-04.png',
    width: 96,
    height: 96,
  },
  {
    key: 'cinnamoroll-pack-05',
    label: '大耳狗 · 05',
    category: 'sanrio',
    character: '大耳狗',
    imageUrl: '/assets/message-stickers/cinnamoroll-pack-05.png',
    width: 96,
    height: 96,
  },
  {
    key: 'cinnamoroll-pack-06',
    label: '大耳狗 · 06',
    category: 'sanrio',
    character: '大耳狗',
    imageUrl: '/assets/message-stickers/cinnamoroll-pack-06.png',
    width: 96,
    height: 96,
  },
  {
    key: 'cinnamoroll-pack-07',
    label: '大耳狗 · 07',
    category: 'sanrio',
    character: '大耳狗',
    imageUrl: '/assets/message-stickers/cinnamoroll-pack-07.png',
    width: 96,
    height: 96,
  },
  {
    key: 'cinnamoroll-pack-08',
    label: '大耳狗 · 08',
    category: 'sanrio',
    character: '大耳狗',
    imageUrl: '/assets/message-stickers/cinnamoroll-pack-08.png',
    width: 96,
    height: 96,
  },
  {
    key: 'cinnamoroll-pack-09',
    label: '大耳狗 · 09',
    category: 'sanrio',
    character: '大耳狗',
    imageUrl: '/assets/message-stickers/cinnamoroll-pack-09.png',
    width: 96,
    height: 96,
  },
  {
    key: 'cinnamoroll-pack-10',
    label: '大耳狗 · 10',
    category: 'sanrio',
    character: '大耳狗',
    imageUrl: '/assets/message-stickers/cinnamoroll-pack-10.png',
    width: 96,
    height: 96,
  },
  {
    key: 'cinnamoroll-pack-11',
    label: '大耳狗 · 11',
    category: 'sanrio',
    character: '大耳狗',
    imageUrl: '/assets/message-stickers/cinnamoroll-pack-11.png',
    width: 96,
    height: 96,
  },
  {
    key: 'cinnamoroll-pack-12',
    label: '大耳狗 · 12',
    category: 'sanrio',
    character: '大耳狗',
    imageUrl: '/assets/message-stickers/cinnamoroll-pack-12.png',
    width: 96,
    height: 96,
  },
  {
    key: 'cinnamoroll-pack-13',
    label: '大耳狗 · 13',
    category: 'sanrio',
    character: '大耳狗',
    imageUrl: '/assets/message-stickers/cinnamoroll-pack-13.png',
    width: 96,
    height: 96,
  },
  {
    key: 'cinnamoroll-pack-14',
    label: '大耳狗 · 14',
    category: 'sanrio',
    character: '大耳狗',
    imageUrl: '/assets/message-stickers/cinnamoroll-pack-14.png',
    width: 96,
    height: 96,
  },
  {
    key: 'pochacco-pack-01',
    label: '帕恰狗 · 01',
    category: 'sanrio',
    character: '帕恰狗',
    imageUrl: '/assets/message-stickers/pochacco-pack-01.png',
    width: 92,
    height: 92,
  },
  {
    key: 'pochacco-pack-02',
    label: '帕恰狗 · 02',
    category: 'sanrio',
    character: '帕恰狗',
    imageUrl: '/assets/message-stickers/pochacco-pack-02.png',
    width: 92,
    height: 92,
  },
  {
    key: 'pochacco-pack-03',
    label: '帕恰狗 · 03',
    category: 'sanrio',
    character: '帕恰狗',
    imageUrl: '/assets/message-stickers/pochacco-pack-03.png',
    width: 92,
    height: 92,
  },
  {
    key: 'pochacco-pack-04',
    label: '帕恰狗 · 04',
    category: 'sanrio',
    character: '帕恰狗',
    imageUrl: '/assets/message-stickers/pochacco-pack-04.png',
    width: 92,
    height: 92,
  },
  {
    key: 'pochacco-pack-05',
    label: '帕恰狗 · 05',
    category: 'sanrio',
    character: '帕恰狗',
    imageUrl: '/assets/message-stickers/pochacco-pack-05.png',
    width: 92,
    height: 92,
  },
  {
    key: 'pochacco-pack-06',
    label: '帕恰狗 · 06',
    category: 'sanrio',
    character: '帕恰狗',
    imageUrl: '/assets/message-stickers/pochacco-pack-06.png',
    width: 92,
    height: 92,
  },
  {
    key: 'pochacco-pack-07',
    label: '帕恰狗 · 07',
    category: 'sanrio',
    character: '帕恰狗',
    imageUrl: '/assets/message-stickers/pochacco-pack-07.png',
    width: 92,
    height: 92,
  },
  {
    key: 'pochacco-pack-08',
    label: '帕恰狗 · 08',
    category: 'sanrio',
    character: '帕恰狗',
    imageUrl: '/assets/message-stickers/pochacco-pack-08.png',
    width: 92,
    height: 92,
  },
  {
    key: 'pochacco-pack-09',
    label: '帕恰狗 · 09',
    category: 'sanrio',
    character: '帕恰狗',
    imageUrl: '/assets/message-stickers/pochacco-pack-09.png',
    width: 92,
    height: 92,
  },
  {
    key: 'pochacco-pack-10',
    label: '帕恰狗 · 10',
    category: 'sanrio',
    character: '帕恰狗',
    imageUrl: '/assets/message-stickers/pochacco-pack-10.png',
    width: 92,
    height: 92,
  },
  {
    key: 'nachoneko-pack-01',
    label: '猫猫 · 01',
    category: 'nachoneko',
    character: '甘城猫猫',
    imageUrl: '/assets/message-stickers/nachoneko-pack-01.png',
    width: 96,
    height: 96,
  },
  {
    key: 'nachoneko-pack-02',
    label: '猫猫 · 02',
    category: 'nachoneko',
    character: '甘城猫猫',
    imageUrl: '/assets/message-stickers/nachoneko-pack-02.png',
    width: 96,
    height: 96,
  },
  {
    key: 'nachoneko-pack-03',
    label: '猫猫 · 03',
    category: 'nachoneko',
    character: '甘城猫猫',
    imageUrl: '/assets/message-stickers/nachoneko-pack-03.png',
    width: 96,
    height: 96,
  },
  {
    key: 'nachoneko-pack-04',
    label: '猫猫 · 04',
    category: 'nachoneko',
    character: '甘城猫猫',
    imageUrl: '/assets/message-stickers/nachoneko-pack-04.png',
    width: 96,
    height: 96,
  },
  {
    key: 'nachoneko-pack-05',
    label: '猫猫 · 05',
    category: 'nachoneko',
    character: '甘城猫猫',
    imageUrl: '/assets/message-stickers/nachoneko-pack-05.png',
    width: 96,
    height: 96,
  },
  {
    key: 'nachoneko-pack-06',
    label: '猫猫 · 06',
    category: 'nachoneko',
    character: '甘城猫猫',
    imageUrl: '/assets/message-stickers/nachoneko-pack-06.png',
    width: 96,
    height: 96,
  },
  {
    key: 'nachoneko-pack-07',
    label: '猫猫 · 07',
    category: 'nachoneko',
    character: '甘城猫猫',
    imageUrl: '/assets/message-stickers/nachoneko-pack-07.png',
    width: 96,
    height: 96,
  },
  {
    key: 'nachoneko-pack-08',
    label: '猫猫 · 08',
    category: 'nachoneko',
    character: '甘城猫猫',
    imageUrl: '/assets/message-stickers/nachoneko-pack-08.png',
    width: 96,
    height: 96,
  },
  {
    key: 'nachoneko-pack-09',
    label: '猫猫 · 09',
    category: 'nachoneko',
    character: '甘城猫猫',
    imageUrl: '/assets/message-stickers/nachoneko-pack-09.png',
    width: 96,
    height: 96,
  },
  {
    key: 'nachoneko-pack-10',
    label: '猫猫 · 10',
    category: 'nachoneko',
    character: '甘城猫猫',
    imageUrl: '/assets/message-stickers/nachoneko-pack-10.png',
    width: 96,
    height: 96,
  },
  {
    key: 'nachoneko-pack-11',
    label: '猫猫 · 11',
    category: 'nachoneko',
    character: '甘城猫猫',
    imageUrl: '/assets/message-stickers/nachoneko-pack-11.png',
    width: 96,
    height: 96,
  },
  {
    key: 'nachoneko-pack-12',
    label: '猫猫 · 12',
    category: 'nachoneko',
    character: '甘城猫猫',
    imageUrl: '/assets/message-stickers/nachoneko-pack-12.png',
    width: 96,
    height: 96,
  },
  {
    key: 'nachoneko-pack-13',
    label: '猫猫 · 13',
    category: 'nachoneko',
    character: '甘城猫猫',
    imageUrl: '/assets/message-stickers/nachoneko-pack-13.png',
    width: 96,
    height: 96,
  },
  {
    key: 'nachoneko-pack-14',
    label: '猫猫 · 14',
    category: 'nachoneko',
    character: '甘城猫猫',
    imageUrl: '/assets/message-stickers/nachoneko-pack-14.png',
    width: 96,
    height: 96,
  },
  {
    key: 'nachoneko-pack-15',
    label: '猫猫 · 15',
    category: 'nachoneko',
    character: '甘城猫猫',
    imageUrl: '/assets/message-stickers/nachoneko-pack-15.png',
    width: 96,
    height: 96,
  },
  {
    key: 'nachoneko-pack-16',
    label: '猫猫 · 16',
    category: 'nachoneko',
    character: '甘城猫猫',
    imageUrl: '/assets/message-stickers/nachoneko-pack-16.png',
    width: 96,
    height: 96,
  },
  {
    key: 'nachoneko-pack-17',
    label: '猫猫 · 17',
    category: 'nachoneko',
    character: '甘城猫猫',
    imageUrl: '/assets/message-stickers/nachoneko-pack-17.png',
    width: 96,
    height: 96,
  },
  {
    key: 'nekoha-shizuku-pack-01',
    label: '雫 · 01',
    category: 'nekoha-shizuku',
    character: '猫羽雫',
    imageUrl: '/assets/message-stickers/nekoha-shizuku-pack-01.png',
    width: 96,
    height: 96,
  },
  {
    key: 'nekoha-shizuku-pack-02',
    label: '雫 · 02',
    category: 'nekoha-shizuku',
    character: '猫羽雫',
    imageUrl: '/assets/message-stickers/nekoha-shizuku-pack-02.png',
    width: 96,
    height: 96,
  },
  {
    key: 'nekoha-shizuku-pack-03',
    label: '雫 · 03',
    category: 'nekoha-shizuku',
    character: '猫羽雫',
    imageUrl: '/assets/message-stickers/nekoha-shizuku-pack-03.png',
    width: 96,
    height: 96,
  },
  {
    key: 'nekoha-shizuku-pack-04',
    label: '雫 · 04',
    category: 'nekoha-shizuku',
    character: '猫羽雫',
    imageUrl: '/assets/message-stickers/nekoha-shizuku-pack-04.png',
    width: 96,
    height: 96,
  },
  {
    key: 'nekoha-shizuku-pack-05',
    label: '雫 · 05',
    category: 'nekoha-shizuku',
    character: '猫羽雫',
    imageUrl: '/assets/message-stickers/nekoha-shizuku-pack-05.png',
    width: 96,
    height: 96,
  },
  {
    key: 'nekoha-shizuku-pack-06',
    label: '雫 · 06',
    category: 'nekoha-shizuku',
    character: '猫羽雫',
    imageUrl: '/assets/message-stickers/nekoha-shizuku-pack-06.png',
    width: 96,
    height: 96,
  },
  {
    key: 'nekoha-shizuku-pack-07',
    label: '雫 · 07',
    category: 'nekoha-shizuku',
    character: '猫羽雫',
    imageUrl: '/assets/message-stickers/nekoha-shizuku-pack-07.png',
    width: 96,
    height: 96,
  },
  {
    key: 'nekoha-shizuku-pack-08',
    label: '雫 · 08',
    category: 'nekoha-shizuku',
    character: '猫羽雫',
    imageUrl: '/assets/message-stickers/nekoha-shizuku-pack-08.png',
    width: 96,
    height: 96,
  },
  {
    key: 'nekoha-shizuku-pack-09',
    label: '雫 · 09',
    category: 'nekoha-shizuku',
    character: '猫羽雫',
    imageUrl: '/assets/message-stickers/nekoha-shizuku-pack-09.png',
    width: 96,
    height: 96,
  },
  {
    key: 'nekoha-shizuku-pack-10',
    label: '雫 · 10',
    category: 'nekoha-shizuku',
    character: '猫羽雫',
    imageUrl: '/assets/message-stickers/nekoha-shizuku-pack-10.png',
    width: 96,
    height: 96,
  },
  {
    key: 'nekoha-shizuku-pack-11',
    label: '雫 · 11',
    category: 'nekoha-shizuku',
    character: '猫羽雫',
    imageUrl: '/assets/message-stickers/nekoha-shizuku-pack-11.png',
    width: 96,
    height: 96,
  },
  {
    key: 'nekoha-shizuku-pack-12',
    label: '雫 · 12',
    category: 'nekoha-shizuku',
    character: '猫羽雫',
    imageUrl: '/assets/message-stickers/nekoha-shizuku-pack-12.png',
    width: 96,
    height: 96,
  },
  {
    key: 'nekoha-shizuku-pack-13',
    label: '雫 · 13',
    category: 'nekoha-shizuku',
    character: '猫羽雫',
    imageUrl: '/assets/message-stickers/nekoha-shizuku-pack-13.png',
    width: 96,
    height: 96,
  },
  {
    key: 'nekoha-shizuku-pack-14',
    label: '雫 · 14',
    category: 'nekoha-shizuku',
    character: '猫羽雫',
    imageUrl: '/assets/message-stickers/nekoha-shizuku-pack-14.png',
    width: 96,
    height: 96,
  },
  {
    key: 'nekoha-shizuku-pack-15',
    label: '雫 · 15',
    category: 'nekoha-shizuku',
    character: '猫羽雫',
    imageUrl: '/assets/message-stickers/nekoha-shizuku-pack-15.png',
    width: 96,
    height: 96,
  },
  {
    key: 'nekoha-shizuku-pack-16',
    label: '雫 · 16',
    category: 'nekoha-shizuku',
    character: '猫羽雫',
    imageUrl: '/assets/message-stickers/nekoha-shizuku-pack-16.png',
    width: 96,
    height: 96,
  },
  {
    key: 'nekoha-shizuku-pack-17',
    label: '雫 · 17',
    category: 'nekoha-shizuku',
    character: '猫羽雫',
    imageUrl: '/assets/message-stickers/nekoha-shizuku-pack-17.png',
    width: 96,
    height: 96,
  },
  {
    key: 'journal-heart-02',
    label: '小爱心',
    category: 'journal',
    character: '手帐装饰',
    imageUrl: '/assets/message-stickers/journal-heart-02.png',
    width: 80,
    height: 80,
  },
  {
    key: 'journal-star-02',
    label: '小星星',
    category: 'journal',
    character: '手帐装饰',
    imageUrl: '/assets/message-stickers/journal-star-02.png',
    width: 80,
    height: 80,
  },
  {
    key: 'journal-clover-02',
    label: '四叶草',
    category: 'journal',
    character: '手帐装饰',
    imageUrl: '/assets/message-stickers/journal-clover-02.png',
    width: 80,
    height: 80,
  },
  {
    key: 'journal-ribbon-02',
    label: '蝴蝶结',
    category: 'journal',
    character: '手帐装饰',
    imageUrl: '/assets/message-stickers/journal-ribbon-02.png',
    width: 80,
    height: 80,
  },
  {
    key: 'journal-rainbow-02',
    label: '小彩虹',
    category: 'journal',
    character: '手帐装饰',
    imageUrl: '/assets/message-stickers/journal-rainbow-02.png',
    width: 80,
    height: 80,
  },
  {
    key: 'journal-flower-02',
    label: '小花花',
    category: 'journal',
    character: '手帐装饰',
    imageUrl: '/assets/message-stickers/journal-flower-02.png',
    width: 80,
    height: 80,
  },
  {
    key: 'journal-leaf-02',
    label: '一片叶子',
    category: 'journal',
    character: '手帐装饰',
    imageUrl: '/assets/message-stickers/journal-leaf-02.png',
    width: 80,
    height: 80,
  },
  {
    key: 'journal-cloud-02',
    label: '软软云朵',
    category: 'journal',
    character: '手帐装饰',
    imageUrl: '/assets/message-stickers/journal-cloud-02.png',
    width: 80,
    height: 80,
  },
] as const;

export const MESSAGE_STICKER_BY_KEY = new Map(
  MESSAGE_STICKER_CATALOG.map((item) => [item.key, item] as const),
);
