import { pbkdf2Sync } from "node:crypto";
import { describe, expect, it } from "vitest";

import { verifyPassword } from "../src/auth";

function makePasswordHash(password: string, iterations: number): string {
  const salt = Buffer.from("auth-password-compat-salt");
  const hash = pbkdf2Sync(password, salt, iterations, 32, "sha256");
  return `pbkdf2$sha256$${iterations}$${salt.toString("base64url")}$${hash.toString("base64url")}`;
}

describe("admin password hash compatibility", () => {
  it("accepts the legacy 100000-iteration PBKDF2 hash", async () => {
    await expect(verifyPassword("correct horse", makePasswordHash("correct horse", 100000))).resolves.toBe(true);
  });

  it("accepts the current 310000-iteration PBKDF2 hash generated by the repository script", async () => {
    await expect(verifyPassword("correct horse", makePasswordHash("correct horse", 310000))).resolves.toBe(true);
  });

  it("rejects unsupported PBKDF2 iteration counts", async () => {
    await expect(verifyPassword("correct horse", makePasswordHash("correct horse", 200000))).resolves.toBe(false);
  });
});
