#!/usr/bin/env node
import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";

const VALID_CATEGORIES = new Set(["游戏", "音乐", "生活", "吐槽"]);
const DEFAULT_INPUT = "src/data/moments.json";
const DEFAULT_OUTPUT = ".tmp/moments-import.sql";
const LEGACY_R2_BASE_URL = "https://pub-6108779417b647c592c51538e44c8bd0.r2.dev";
const PUBLIC_MEDIA_BASE_URL = "https://media.lidure.xyz";

async function main() {
  const args = parseArgs(process.argv.slice(2));
  const inputPath = args.input ?? DEFAULT_INPUT;
  const outputPath = args.output ?? DEFAULT_OUTPUT;

  const raw = await readFile(inputPath, "utf8");
  const moments = JSON.parse(raw);
  if (!Array.isArray(moments)) {
    throw new Error("Input moments JSON must be an array.");
  }

  const normalized = moments.map((moment, index) => normalizeMoment(moment, index));
  const sql = renderSql(normalized);

  await mkdir(path.dirname(outputPath), { recursive: true });
  await writeFile(outputPath, sql, "utf8");

  const mediaCount = normalized.reduce((total, moment) => total + moment.media.length, 0);
  console.log(`Wrote ${normalized.length} moments and ${mediaCount} media rows to ${outputPath}`);
}

function parseArgs(argv) {
  const args = {};
  for (let index = 0; index < argv.length; index += 1) {
    const flag = argv[index];
    const value = argv[index + 1];
    if (flag === "--input" && value) {
      args.input = value;
      index += 1;
      continue;
    }

    if (flag === "--output" && value) {
      args.output = value;
      index += 1;
      continue;
    }

    throw new Error(`Unknown or incomplete argument: ${flag}`);
  }

  return args;
}

function normalizeMoment(moment, index) {
  if (!moment || typeof moment !== "object" || Array.isArray(moment)) {
    throw new Error(`Moment at index ${index} must be an object.`);
  }

  const date = stringField(moment.date);
  if (!isValidMomentDate(date)) {
    throw new Error(`Moment at index ${index} has an invalid date.`);
  }

  const category = stringField(moment.category);
  if (!VALID_CATEGORIES.has(category)) {
    throw new Error(`Moment at index ${index} has an invalid category.`);
  }

  const text = stringField(moment.text);
  if (!text) {
    throw new Error(`Moment at index ${index} must include text.`);
  }

  const link = stringField(moment.link);
  if (link && !isHttpUrl(link)) {
    throw new Error(`Moment at index ${index} has an invalid link.`);
  }

  const id = stableMomentId(date, category, text, link);
  const media = normalizeImages(moment.images, id);
  const createdAt = toCreatedAt(date);

  return {
    id,
    date,
    category,
    text,
    link,
    createdAt,
    media,
  };
}

function normalizeImages(images, momentId) {
  if (images == null) return [];
  if (!Array.isArray(images)) {
    throw new Error(`Moment ${momentId} images must be an array.`);
  }

  return images.map((rawUrl, index) => {
    const url = stringField(rawUrl);
    if (!isHttpUrl(url)) {
      throw new Error(`Moment ${momentId} image ${index} must be an http(s) URL.`);
    }

    return {
      id: stableMediaId(momentId, "image", normalizeLegacyMediaUrl(url), index),
      kind: "image",
      url: normalizeLegacyMediaUrl(url),
      sortOrder: index,
    };
  });
}

function renderSql(moments) {
  const lines = [
    "-- Generated by scripts/import-moments.mjs. Safe to run repeatedly.",
    "BEGIN TRANSACTION;",
  ];

  for (const moment of moments) {
    lines.push(
      `INSERT OR IGNORE INTO moments (id, date, category, text, link, created_at, updated_at) VALUES (${[
        sqlString(moment.id),
        sqlString(moment.date),
        sqlString(moment.category),
        sqlString(moment.text),
        moment.link ? sqlString(moment.link) : "NULL",
        sqlString(moment.createdAt),
        sqlString(moment.createdAt),
      ].join(", ")});`
    );

    for (const media of moment.media) {
      lines.push(
        `INSERT OR IGNORE INTO moment_media (id, moment_id, kind, url, sort_order, created_at) VALUES (${[
          sqlString(media.id),
          sqlString(moment.id),
          sqlString(media.kind),
          sqlString(media.url),
          String(media.sortOrder),
          sqlString(moment.createdAt),
        ].join(", ")});`
      );
    }
  }

  lines.push("COMMIT;", "");
  return lines.join("\n");
}

function stableMomentId(date, category, text, link) {
  return createHash("sha256")
    .update(`${date}\0${category}\0${text}\0${link}`)
    .digest("hex")
    .slice(0, 32);
}

function stableMediaId(momentId, kind, url, sortOrder) {
  return createHash("sha256")
    .update(`${momentId}\0${kind}\0${url}\0${sortOrder}`)
    .digest("hex")
    .slice(0, 32);
}

function stringField(value) {
  return typeof value === "string" ? value.trim() : "";
}

function isValidMomentDate(value) {
  if (!/^\d{4}-\d{2}-\d{2}(T\d{2}:\d{2})?$/.test(value)) {
    return false;
  }

  return Number.isFinite(Date.parse(value.includes("T") ? `${value}:00Z` : `${value}T00:00:00Z`));
}

function toCreatedAt(date) {
  return new Date(date.includes("T") ? `${date}:00Z` : `${date}T00:00:00Z`).toISOString();
}

function isHttpUrl(value) {
  try {
    const url = new URL(value);
    return url.protocol === "http:" || url.protocol === "https:";
  } catch {
    return false;
  }
}

function normalizeLegacyMediaUrl(value) {
  return value.startsWith(`${LEGACY_R2_BASE_URL}/`)
    ? `${PUBLIC_MEDIA_BASE_URL}/${value.slice(LEGACY_R2_BASE_URL.length + 1)}`
    : value;
}

function sqlString(value) {
  return `'${String(value).replaceAll("'", "''")}'`;
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : String(error));
  process.exitCode = 1;
});
